### PR TITLE
add routeImportAs to solve class name conflict

### PR DESCRIPTION
**Pull request by lvyandev**
Add the `routeImportAs` annotation field in `FFRoute` to avoid conflict when same class names found in different directories.
This field is optional. if `routeImportAs` is set, current route will be imported as the value.

### CODE REVIEW

**Comment by zmtzawqlp** [comment]
1. i don't think this function is necessary. Take care of your ClassName will save more time.
2. take care of the Pages(Classes) are in different packages. i didn't see any code to handle this.

**Comment by lvyandev** [comment]
我不这样认为，我觉得这个应该作为可选功能，否则import为什么还需要as

另外一般情况下，一个项目里面的页面较少，保持类名的独立性是有必要的。

然而很多业务导向的项目，虽然每个页面的业务不一样，但是每个业务内页面可能长的差不多，有时候会复制一些类然后修改业务逻辑。
而在业务模块比较多的情况下就需要重命名很多类，也有类名过长的问题。

因此我觉得还是有一定必要性的

**Comment by zmtzawqlp** [comment]
Page is not a function, they should be unique. if they have different  business logic, why make it the same name?

**Comment by zmtzawqlp** [comment]
I can't find the reason why you would rather change the comment than the Class Name

**Pull request closed without merging**
